# Generated by Django 4.2.6 on 2023-11-17 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='audio_files',
            new_name='songs',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
