# Generated by Django 4.2.6 on 2023-12-05 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_rename_audio_files_playlist_songs_delete_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='thumbnail',
        ),
    ]
