# Generated by Django 4.2.1 on 2023-05-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiomanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
