# Generated by Django 3.2.12 on 2023-05-25 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiomanager', '0002_audiofile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='artist',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='runtime',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
