# Generated by Django 3.2.12 on 2023-06-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiomanager', '0004_audiofile_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='runtime',
            field=models.CharField(default='0:00', max_length=10),
        ),
    ]
