# Generated by Django 3.2.12 on 2023-06-01 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiomanager', '0005_alter_audiofile_runtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='audio_file',
            new_name='song',
        ),
    ]
