# Generated by Django 3.2.12 on 2023-06-01 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiomanager', '0006_rename_audio_file_audiofile_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='song',
            new_name='url',
        ),
    ]
