# Generated by Django 4.2.6 on 2023-11-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiomanager', '0007_rename_song_audiofile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='url',
            field=models.FileField(upload_to='audiomanager/audio/'),
        ),
    ]
